### PR TITLE
Compile with stable rust

### PR DESCRIPTION
**Pull request by wngr**
Hey there,

thanks for your lib! I did a small change in order to make it compile with stable rust (used 1.48.0 as the time of writing).

I didn't come up with a better way than adding the `_phantom` member to the `Trap` struct -- do you have another idea how to achieve that?

### CODE REVIEW

**Comment by wngr** [comment]
Any chance this is going to be merged / released?
Ping @elizagamedev

**Comment by adalinesimonian** [comment]
Is this repository actively maintained anymore? This PR has been sitting around for some months now.

**Comment by elizagamedev** [comment]
Sorry about that, I need to do something about my github notifications :sweat:

**Comment by adalinesimonian** [comment]
No problem! Thanks for the merge. Cheers 🍻

**Comment by wngr** [comment]
Awesome. Could you cut a new release?

**Comment by elizagamedev** [comment]
Yeah, I'll see if I can do that sometime this week.

**Comment by elizagamedev** [comment]
Sorry for the delay, version 3.1 is now published to crates.io

**Comment by wngr** [comment]
Great, thanks!

**Pull request merged**
